[package]
name = "criminal_heatmap"
version = "0.8.0"
authors = ["Elías Puma <elpumitaelias@gmail.com>"]

[dependencies]
record = { path = "../libs/record/" }
kernel = { path = "../libs/kernel/" }
clustering = { path = "../libs/clustering/" }