[package]
name = "addr2coord"
version = "0.1.0"
authors = ["Elías Puma <elpumitaelias@gmail.com>"]

[dependencies]
rustc-serialize = "0.3.24"
quick-csv = "0.1.6"
csv = "0.14"
futures = "0.1.14"
hyper = "0.11.0"
tokio-core = "0.1.8"
serde_json = "1.0.2"